import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}

// Al ejecutar un npm run build, podras ver que en este caso hay 4 páginas web estaticas
// Route (app)
// ┌ ○ /
// ├ ○ /_not-found
// ├ ○ /dashboard/counter
// └ ○ /dashboard/main

// ○  (Static)  prerendered as static content

// Aqui hay un comportamiento diferente, porque la ruta /dashboard/pokemon/[id] es dinámica
// y por lo tanto no se puede prerenderizar como static content

// Route (app)
// ┌ ○ /
// ├ ○ /_not-found
// ├ ○ /dashboard/counter
// ├ ○ /dashboard/main
// ├ ƒ /dashboard/pokemon/[id]
// └ ○ /dashboard/pokemons

// ○  (Static)   prerendered as static content
// ƒ  (Dynamic)  server-rendered on demand
