import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import { Provider } from "react-redux";
// import { store } from "@/store";
import { Providers } from "@/store/Providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {/* {children} */}

        {/* 
          MANEJO DEL ESTADO GLOBAL
          https://redux-toolkit.js.org/introduction/getting-started
          Redux Toolkit es una librería que facilita el uso de Redux en aplicaciones React
          Permite manejar el estado de la aplicación de manera más sencilla y eficiente
          Se recomienda usar Redux Toolkit en lugar de Redux puro

          Ejecuta el comando: npm install @reduxjs/toolkit react-redux

          Provider de 'react-redux' ocupa un HOC (Higher Order Component) para envolver la aplicación
          Cualquier componente que necesite acceder al store debe estar dentro de este HOC

          El problema es que se quiere crear un contexto y debe ser un componente del lado del cliente
          con 'use client'

          Pero si colocas un 'use client' en el layout.tsx, entonces todos los componentes que estén
          dentro de este layout serán del lado del cliente, no será permitido renderizar del lado del servidor
        */}

        {/* <Provider store={store}>{children}</Provider> */}

        {/* Para aquello crea un archivo Providers.tsx dentro de la carpeta store */}
        {/* Y luego importa el componente Providers en este archivo */}
        <Providers>{children}</Providers>

        {/* Aunque es una solución temporal, funciona, pero no es la mejor práctica */}

        {/* Para mandar información generada del lado del servidor al redux, se tiene que hacer
        mediante un action que se ejecute en el cliente, hay un punto intermedio entre el servidor
        y el cliente */}
      </body>
    </html>
  );
}

// Al ejecutar un npm run build, podras ver que en este caso hay 4 páginas web estaticas
// Route (app)
// ┌ ○ /
// ├ ○ /_not-found
// ├ ○ /dashboard/counter
// └ ○ /dashboard/main

// ○  (Static)  prerendered as static content

// Aqui hay un comportamiento diferente, porque la ruta /dashboard/pokemon/[id] es dinámica
// y por lo tanto no se puede prerenderizar como static content

// Route (app)
// ┌ ○ /
// ├ ○ /_not-found
// ├ ○ /dashboard/counter
// ├ ○ /dashboard/main
// ├ ƒ /dashboard/pokemon/[id]
// └ ○ /dashboard/pokemons

// ○  (Static)   prerendered as static content
// ƒ  (Dynamic)  server-rendered on demand

// Si hubiera la función generateStaticParams, entonces las páginas dinámicas se prerenderizarían como static content
// Route (app)
// ┌ ○ /
// ├ ○ /_not-found
// ├ ○ /dashboard/counter
// ├ ○ /dashboard/main
// ├ ● /dashboard/pokemon/[id]
// │ ├ /dashboard/pokemon/1
// │ ├ /dashboard/pokemon/2
// │ ├ /dashboard/pokemon/3
// │ └ [+7 more paths]
// └ ○ /dashboard/pokemons

// ○  (Static)  prerendered as static content
// ●  (SSG)     prerendered as static HTML (uses generateStaticParams)

// Generación de páginas estáticas para 151 pokemones tanto por su ID como por su nombre
// La propiedad revalidate sirve para indicar cada cuánto tiempo se debe regenerar la página
// Route (app)                        Revalidate  Expire
// ┌ ○ /
// ├ ○ /_not-found
// ├ ○ /dashboard/counter
// ├ ○ /dashboard/main
// ├ ● /dashboard/pokemon/[id]               30d      1y
// │ ├ /dashboard/pokemon/1                  30d      1y
// │ ├ /dashboard/pokemon/2                  30d      1y
// │ ├ /dashboard/pokemon/3                  30d      1y
// │ └ [+148 more paths]
// ├ ○ /dashboard/pokemons
// └ ● /dashboard/pokemons/[name]            30d      1y
//   ├ /dashboard/pokemons/bulbasaur         30d      1y
//   ├ /dashboard/pokemons/ivysaur           30d      1y
//   ├ /dashboard/pokemons/venusaur          30d      1y
//   └ [+148 more paths]

// ○  (Static)  prerendered as static content
// ●  (SSG)     prerendered as static HTML (uses generateStaticParams)

// Generación de páginas de todo el proyecto, ahora hay páginas estáticas y dinámicas
// Además de un endpoint API
// Partial Pretender (PPR) - Renderizado híbrido que tiene partes estáticas y dinámicas
// Route (app)                        Revalidate  Expire
// ┌ ○ /
// ├ ○ /_not-found
// ├ ƒ /api/counter
// ├ ○ /dashboard/counter
// ├ ○ /dashboard/favorites                   1m      1y
// ├ ○ /dashboard/main
// ├ ◐ /dashboard/pokemon/[id]               30d      1y
// │ ├ /dashboard/pokemon/[id]               30d      1y
// │ ├ /dashboard/pokemon/1                  30d      1y
// │ ├ /dashboard/pokemon/2                  30d      1y
// │ └ [+149 more paths]
// ├ ○ /dashboard/pokemons                    1m      1y
// ├ ◐ /dashboard/pokemons/[name]            30d      1y
// │ ├ /dashboard/pokemons/[name]            30d      1y
// │ ├ /dashboard/pokemons/bulbasaur         30d      1y
// │ ├ /dashboard/pokemons/ivysaur           30d      1y
// │ └ [+149 more paths]
// └ ○ /dashboard/random                     10s      1d

// ○  (Static)             prerendered as static content
// ◐  (Partial Prerender)  prerendered as static HTML with dynamic server-streamed content
// ƒ  (Dynamic)            server-rendered on demand
